clear all;
close all; 
clc;

syms m M R Jw n Jm L n a beta fw g W J_psi Jw vl vr J_phi x1 x2 x3 x4 x5 x6 x7 x8 x9
f1 = ((2*m+M)*R^2+2*Jw+2*n^2*Jm)*x3+(M*R*L*cos(x4)-2*n^2*Jm)*x6-M*L*R*x5^2*sin(x4)-a*(vl+vr)+2*(beta+fw)*x2-2*beta*x5
f2 = (M*L*R*cos(x4)-2*n^2*Jm)*x3+(M*L^2+J_psi+2*n^2*Jm)*x6-M*g*L*sin(x4)-M*L^2*x8^2*sin(x4)*cos(x4)+a*(vl+vr)-2*beta*x2+2*beta*x5
f3 = (0.5*m*W^2+J_phi+W^2/2/R^2*(Jw+n^2*Jm)+M*L^2*(sin(x4))^2)*x9+2*M*L^2*x5*x8*sin(x4)*cos(x4)-W/2/R*a*(vr-vl)+W^2/2/R^2*(beta+fw)*x8

[x3,x6,x9] = solve(f1,f2,f3,x3,x6,x9)

%% Tính ra theo các bi?n
%Theo bien
%x3 =(J_psi*a*vl + J_psi*a*vr - 2*J_psi*beta*x2 + 2*J_psi*beta*x5 - 2*J_psi*fw*x2 + L^2*M*a*vl + L^2*M*a*vr - 2*L^2*M*beta*x2 + 2*L^2*M*beta*x5 - 2*L^2*M*fw*x2 - 4*Jm*fw*n^2*x2 + L^3*M^2*R*x5^2*sin(x4) - 2*L*M*R*beta*x2*cos(x4) + 2*L*M*R*beta*x5*cos(x4) - L^3*M^2*R*x8^2*cos(x4)^2*sin(x4) - L^2*M^2*R*g*cos(x4)*sin(x4) + J_psi*L*M*R*x5^2*sin(x4) + 2*Jm*L*M*g*n^2*sin(x4) + L*M*R*a*vl*cos(x4) + L*M*R*a*vr*cos(x4) + 2*Jm*L^2*M*n^2*x8^2*cos(x4)*sin(x4) + 2*Jm*L*M*R*n^2*x5^2*sin(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4))
%x6 = -(2*Jw*a*vl + 2*Jw*a*vr - 4*Jw*beta*x2 + 4*Jw*beta*x5 + M*R^2*a*vl + M*R^2*a*vr - 2*M*R^2*beta*x2 + 2*M*R^2*beta*x5 + 2*R^2*a*m*vl + 2*R^2*a*m*vr + 4*Jm*fw*n^2*x2 - 4*R^2*beta*m*x2 + 4*R^2*beta*m*x5 - L*M^2*R^2*g*sin(x4) - 2*Jw*L*M*g*sin(x4) - 2*L*M*R*beta*x2*cos(x4) + 2*L*M*R*beta*x5*cos(x4) - 2*L*M*R*fw*x2*cos(x4) + L^2*M^2*R^2*x5^2*cos(x4)*sin(x4) - L^2*M^2*R^2*x8^2*cos(x4)*sin(x4) - 2*Jw*L^2*M*x8^2*cos(x4)*sin(x4) - 2*Jm*L*M*g*n^2*sin(x4) - 2*L*M*R^2*g*m*sin(x4) + L*M*R*a*vl*cos(x4) + L*M*R*a*vr*cos(x4) - 2*Jm*L^2*M*n^2*x8^2*cos(x4)*sin(x4) - 2*L^2*M*R^2*m*x8^2*cos(x4)*sin(x4) - 2*Jm*L*M*R*n^2*x5^2*sin(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4))
%x9 =-(W^2*beta*x8 + W^2*fw*x8 + R*W*a*vl - R*W*a*vr + 4*L^2*M*R^2*x5*x8*cos(x4)*sin(x4))/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2)

%Ta có h1=x3, h2=x6, h3=x9;
%h1 = (J_psi*a*vl+J_psi*a*vr-2*J_psi*beta*x2+2*J_psi*beta*x5-2*J_psi*fw*x2+L^2*M*a*vl+L^2*M*a*vr-2*L^2*M*beta*x2+2*L^2*M*beta*x5-2*L^2*M*fw*x2-4*Jm*fw*n^2*x2+L^3*M^2*R*x5^2*sin(x4)-2*L*M*R*beta*x2*cos(x4)+2*L*M*R*beta*x5*cos(x4)-L^3*M^2*R*x8^2*cos(x4)^2*sin(x4)-L^2*M^2*R*g*cos(x4)*sin(x4)+J_psi*L*M*R*x5^2*sin(x4)+2*Jm*L*M*g*n^2*sin(x4)+L*M*R*a*vl*cos(x4)+L*M*R*a*vr*cos(x4)+2*Jm*L^2*M*n^2*x8^2*cos(x4)*sin(x4)+2*Jm*L*M*R*n^2*x5^2*sin(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)) 
%h2 = -(2*Jw*a*vl + 2*Jw*a*vr - 4*Jw*beta*x2 + 4*Jw*beta*x5 + M*R^2*a*vl + M*R^2*a*vr - 2*M*R^2*beta*x2 + 2*M*R^2*beta*x5 + 2*R^2*a*m*vl + 2*R^2*a*m*vr + 4*Jm*fw*n^2*x2 - 4*R^2*beta*m*x2 + 4*R^2*beta*m*x5 - L*M^2*R^2*g*sin(x4) - 2*Jw*L*M*g*sin(x4) - 2*L*M*R*beta*x2*cos(x4) + 2*L*M*R*beta*x5*cos(x4) - 2*L*M*R*fw*x2*cos(x4) + L^2*M^2*R^2*x5^2*cos(x4)*sin(x4) - L^2*M^2*R^2*x8^2*cos(x4)*sin(x4) - 2*Jw*L^2*M*x8^2*cos(x4)*sin(x4) - 2*Jm*L*M*g*n^2*sin(x4) - 2*L*M*R^2*g*m*sin(x4) + L*M*R*a*vl*cos(x4) + L*M*R*a*vr*cos(x4) - 2*Jm*L^2*M*n^2*x8^2*cos(x4)*sin(x4) - 2*L^2*M*R^2*m*x8^2*cos(x4)*sin(x4) - 2*Jm*L*M*R*n^2*x5^2*sin(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4))
%h3 = -(W^2*beta*x8 + W^2*fw*x8 + R*W*a*vl - R*W*a*vr + 4*L^2*M*R^2*x5*x8*cos(x4)*sin(x4))/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2)

%Theo Function block
%teta_dd =(J_psi*a*vl + J_psi*a*vr - 2*J_psi*beta*teta_d + 2*J_psi*beta*psi_d - 2*J_psi*fw*teta_d + L^2*M*a*vl + L^2*M*a*vr - 2*L^2*M*beta*teta_d + 2*L^2*M*beta*psi_d - 2*L^2*M*fw*teta_d - 4*Jm*fw*n^2*teta_d + L^3*M^2*R*psi_d^2*sin(psi) - 2*L*M*R*beta*teta_d*cos(psi) + 2*L*M*R*beta*psi_d*cos(psi) - L^3*M^2*R*phi_d^2*cos(psi)^2*sin(psi) - L^2*M^2*R*g*cos(psi)*sin(psi) + J_psi*L*M*R*psi_d^2*sin(psi) + 2*Jm*L*M*g*n^2*sin(psi) + L*M*R*a*vl*cos(psi) + L*M*R*a*vr*cos(psi) + 2*Jm*L^2*M*n^2*phi_d^2*cos(psi)*sin(psi) + 2*Jm*L*M*R*n^2*psi_d^2*sin(psi))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(psi)^2 + 4*Jm*L*M*R*n^2*cos(psi))
%psi_dd = -(2*Jw*a*vl + 2*Jw*a*vr - 4*Jw*beta*teta_d + 4*Jw*beta*psi_d + M*R^2*a*vl + M*R^2*a*vr - 2*M*R^2*beta*teta_d + 2*M*R^2*beta*psi_d + 2*R^2*a*m*vl + 2*R^2*a*m*vr + 4*Jm*fw*n^2*teta_d - 4*R^2*beta*m*teta_d + 4*R^2*beta*m*psi_d - L*M^2*R^2*g*sin(psi) - 2*Jw*L*M*g*sin(psi) - 2*L*M*R*beta*teta_d*cos(psi) + 2*L*M*R*beta*psi_d*cos(psi) - 2*L*M*R*fw*teta_d*cos(psi) + L^2*M^2*R^2*psi_d^2*cos(psi)*sin(psi) - L^2*M^2*R^2*phi_d^2*cos(psi)*sin(psi) - 2*Jw*L^2*M*phi_d^2*cos(psi)*sin(psi) - 2*Jm*L*M*g*n^2*sin(psi) - 2*L*M*R^2*g*m*sin(psi) + L*M*R*a*vl*cos(psi) + L*M*R*a*vr*cos(psi) - 2*Jm*L^2*M*n^2*phi_d^2*cos(psi)*sin(psi) - 2*L^2*M*R^2*m*phi_d^2*cos(psi)*sin(psi) - 2*Jm*L*M*R*n^2*psi_d^2*sin(psi))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(psi)^2 + 4*Jm*L*M*R*n^2*cos(psi))
%phi_dd =-(W^2*beta*phi_d + W^2*fw*phi_d + R*W*a*vl - R*W*a*vr + 4*L^2*M*R^2*psi_d*phi_d*cos(psi)*sin(psi))/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(psi)^2)
 
%% Rút g?n b?c
syms m M R Jw n Jm L n a beta fw g W J_psi Jw vl vr J_phi x1 x2 x3 x4 x5 x6 x7 x8 x9
y1 = x2;
y2 = (J_psi*a*vl+J_psi*a*vr-2*J_psi*beta*x2+2*J_psi*beta*x5-2*J_psi*fw*x2+L^2*M*a*vl+L^2*M*a*vr-2*L^2*M*beta*x2+2*L^2*M*beta*x5-2*L^2*M*fw*x2-4*Jm*fw*n^2*x2+L^3*M^2*R*x5^2*sin(x4)-2*L*M*R*beta*x2*cos(x4)+2*L*M*R*beta*x5*cos(x4)-L^3*M^2*R*x8^2*cos(x4)^2*sin(x4)-L^2*M^2*R*g*cos(x4)*sin(x4)+J_psi*L*M*R*x5^2*sin(x4)+2*Jm*L*M*g*n^2*sin(x4)+L*M*R*a*vl*cos(x4)+L*M*R*a*vr*cos(x4)+2*Jm*L^2*M*n^2*x8^2*cos(x4)*sin(x4)+2*Jm*L*M*R*n^2*x5^2*sin(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)) 
y3 = x5;
y4 = -(2*Jw*a*vl + 2*Jw*a*vr - 4*Jw*beta*x2 + 4*Jw*beta*x5 + M*R^2*a*vl + M*R^2*a*vr - 2*M*R^2*beta*x2 + 2*M*R^2*beta*x5 + 2*R^2*a*m*vl + 2*R^2*a*m*vr + 4*Jm*fw*n^2*x2 - 4*R^2*beta*m*x2 + 4*R^2*beta*m*x5 - L*M^2*R^2*g*sin(x4) - 2*Jw*L*M*g*sin(x4) - 2*L*M*R*beta*x2*cos(x4) + 2*L*M*R*beta*x5*cos(x4) - 2*L*M*R*fw*x2*cos(x4) + L^2*M^2*R^2*x5^2*cos(x4)*sin(x4) - L^2*M^2*R^2*x8^2*cos(x4)*sin(x4) - 2*Jw*L^2*M*x8^2*cos(x4)*sin(x4) - 2*Jm*L*M*g*n^2*sin(x4) - 2*L*M*R^2*g*m*sin(x4) + L*M*R*a*vl*cos(x4) + L*M*R*a*vr*cos(x4) - 2*Jm*L^2*M*n^2*x8^2*cos(x4)*sin(x4) - 2*L^2*M*R^2*m*x8^2*cos(x4)*sin(x4) - 2*Jm*L*M*R*n^2*x5^2*sin(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4))
y5 = x8;
y6 = -(W^2*beta*x8 + W^2*fw*x8 + R*W*a*vl - R*W*a*vr + 4*L^2*M*R^2*x5*x8*cos(x4)*sin(x4))/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2)

%% Thông s? ??ng c?
m = 1; %Khoi luong banh xe
M = 5; %Khoi luong robot
R = 0.0725; %ban kinh ban xe
W = 0.24; %Chieu rong robot
D = 0.2; %Chieu sau robot
H = 0.5; %Chieu cao robot
L = 0.18; %khoang cach tu trong tam den truc banh xe
fw = 0.18; %He so ma sat giua banh xe voi mat phang
fm = 0.002; %he so ma sat giua dong co va robot
Jm = 10^-2; %moment quan tinh cua dong co
Jw = m*R^2/2;
J_psi = M*L^2/3;
J_phi = M*(W^2+D^2)/12;
Rm = 50; %Dien tro dong co DC
Kb = 0.468; %he so emf cua dong co
Kt = 0.317; %Momen xoan cua dong co DC
n = 40; %Ty so giam toc
g = 9.81; %Gia toc trong truong
alpha = n*Kt/Rm; beta=n*Kt*Kb/Rm+fm; a =alpha;
T=0.01;


%% Tính ma tr?n A
% A =   [ diff(y1,x1) diff(y1,x2) diff(y1,x4) diff(y1,x5) diff(y1,x7) diff(y1,x8);
%         diff(y2,x1) diff(y2,x2) diff(y2,x4) diff(y2,x5) diff(y2,x7) diff(y2,x8);
%         diff(y3,x1) diff(y3,x2) diff(y3,x4) diff(y3,x5) diff(y3,x7) diff(y3,x8);
%         diff(y4,x1) diff(y4,x2) diff(y4,x4) diff(y4,x5) diff(y4,x7) diff(y4,x8);
%         diff(y5,x1) diff(y5,x2) diff(y5,x4) diff(y5,x5) diff(y5,x7) diff(y5,x8);
%         diff(y6,x1) diff(y6,x2) diff(y6,x4) diff(y6,x5) diff(y6,x7) diff(y6,x8)]
% Ra ma tr?n A theo symbols
% syms m M R Jw n Jm L n a beta fw g W J_psi Jw vl vr J_phi x1 x2 x3 x4 x5 x6 x7 x8 x9
% vl=0; vr=0; x1=0; x2=0; x3=0; x4=0; x5=0; x6=0; x7=0; x8=0; 
% A =[0,                                                                                                                                                                                                                                                                                                                            1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0,                                                                                                                                                                                                                                                                                                                                                             0, 0,                                                                                                                                                                                                                                                                                                                                                                  0;
% 0,       -(2*J_psi*beta + 2*J_psi*fw + 2*L^2*M*beta + 2*L^2*M*fw + 4*Jm*fw*n^2 + 2*L*M*R*beta*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)),                                                                                                                                                                                                                                                                                                               (L^2*M^2*R*g*sin(x4)^2 - L^2*M^2*R*g*cos(x4)^2 - L^3*M^2*R*x8^2*cos(x4)^3 + L^3*M^2*R*x5^2*cos(x4) + 2*L^3*M^2*R*x8^2*cos(x4)*sin(x4)^2 - L*M*R*a*vl*sin(x4) - L*M*R*a*vr*sin(x4) + 2*L*M*R*beta*x2*sin(x4) - 2*L*M*R*beta*x5*sin(x4) + J_psi*L*M*R*x5^2*cos(x4) + 2*Jm*L*M*g*n^2*cos(x4) + 2*Jm*L^2*M*n^2*x8^2*cos(x4)^2 - 2*Jm*L^2*M*n^2*x8^2*sin(x4)^2 + 2*Jm*L*M*R*n^2*x5^2*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)) - ((2*cos(x4)*sin(x4)*L^2*M^2*R^2 - 4*Jm*sin(x4)*L*M*R*n^2)*(J_psi*a*vl + J_psi*a*vr - 2*J_psi*beta*x2 + 2*J_psi*beta*x5 - 2*J_psi*fw*x2 + L^2*M*a*vl + L^2*M*a*vr - 2*L^2*M*beta*x2 + 2*L^2*M*beta*x5 - 2*L^2*M*fw*x2 - 4*Jm*fw*n^2*x2 + L^3*M^2*R*x5^2*sin(x4) - 2*L*M*R*beta*x2*cos(x4) + 2*L*M*R*beta*x5*cos(x4) - L^3*M^2*R*x8^2*cos(x4)^2*sin(x4) - L^2*M^2*R*g*cos(x4)*sin(x4) + J_psi*L*M*R*x5^2*sin(x4) + 2*Jm*L*M*g*n^2*sin(x4) + L*M*R*a*vl*cos(x4) + L*M*R*a*vr*cos(x4) + 2*Jm*L^2*M*n^2*x8^2*cos(x4)*sin(x4) + 2*Jm*L*M*R*n^2*x5^2*sin(x4)))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4))^2, (2*J_psi*beta + 2*L^2*M*beta + 2*L^3*M^2*R*x5*sin(x4) + 2*L*M*R*beta*cos(x4) + 2*J_psi*L*M*R*x5*sin(x4) + 4*Jm*L*M*R*n^2*x5*sin(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)), 0,                                                                   -(2*L^3*M^2*R*x8*cos(x4)^2*sin(x4) - 4*Jm*L^2*M*n^2*x8*cos(x4)*sin(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4));
% 0,                                                                                                                                                                                                                                                                                                                            0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0,                                                                                                                                                                                                                                                                                                                                                             1, 0,                                                                                                                                                                                                                                                                                                                                                                  0;
% 0, (4*Jw*beta + 2*M*R^2*beta - 4*Jm*fw*n^2 + 4*R^2*beta*m + 2*L*M*R*beta*cos(x4) + 2*L*M*R*fw*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)), (L*M^2*R^2*g*cos(x4) - L^2*M^2*R^2*x5^2*cos(x4)^2 + L^2*M^2*R^2*x8^2*cos(x4)^2 + 2*Jw*L*M*g*cos(x4) + L^2*M^2*R^2*x5^2*sin(x4)^2 - L^2*M^2*R^2*x8^2*sin(x4)^2 + 2*Jw*L^2*M*x8^2*cos(x4)^2 - 2*Jw*L^2*M*x8^2*sin(x4)^2 + L*M*R*a*vl*sin(x4) + L*M*R*a*vr*sin(x4) - 2*L*M*R*beta*x2*sin(x4) + 2*L*M*R*beta*x5*sin(x4) - 2*L*M*R*fw*x2*sin(x4) + 2*Jm*L*M*g*n^2*cos(x4) + 2*L*M*R^2*g*m*cos(x4) + 2*Jm*L^2*M*n^2*x8^2*cos(x4)^2 + 2*L^2*M*R^2*m*x8^2*cos(x4)^2 - 2*Jm*L^2*M*n^2*x8^2*sin(x4)^2 - 2*L^2*M*R^2*m*x8^2*sin(x4)^2 + 2*Jm*L*M*R*n^2*x5^2*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)) + ((2*cos(x4)*sin(x4)*L^2*M^2*R^2 - 4*Jm*sin(x4)*L*M*R*n^2)*(2*Jw*a*vl + 2*Jw*a*vr - 4*Jw*beta*x2 + 4*Jw*beta*x5 + M*R^2*a*vl + M*R^2*a*vr - 2*M*R^2*beta*x2 + 2*M*R^2*beta*x5 + 2*R^2*a*m*vl + 2*R^2*a*m*vr + 4*Jm*fw*n^2*x2 - 4*R^2*beta*m*x2 + 4*R^2*beta*m*x5 - L*M^2*R^2*g*sin(x4) - 2*Jw*L*M*g*sin(x4) - 2*L*M*R*beta*x2*cos(x4) + 2*L*M*R*beta*x5*cos(x4) - 2*L*M*R*fw*x2*cos(x4) + L^2*M^2*R^2*x5^2*cos(x4)*sin(x4) - L^2*M^2*R^2*x8^2*cos(x4)*sin(x4) - 2*Jw*L^2*M*x8^2*cos(x4)*sin(x4) - 2*Jm*L*M*g*n^2*sin(x4) - 2*L*M*R^2*g*m*sin(x4) + L*M*R*a*vl*cos(x4) + L*M*R*a*vr*cos(x4) - 2*Jm*L^2*M*n^2*x8^2*cos(x4)*sin(x4) - 2*L^2*M*R^2*m*x8^2*cos(x4)*sin(x4) - 2*Jm*L*M*R*n^2*x5^2*sin(x4)))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4))^2,     -(2*x5*cos(x4)*sin(x4)*L^2*M^2*R^2 - 4*Jm*x5*sin(x4)*L*M*R*n^2 + 2*cos(x4)*beta*L*M*R + 2*beta*M*R^2 + 4*m*beta*R^2 + 4*Jw*beta)/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)), 0, (2*x8*cos(x4)*sin(x4)*L^2*M^2*R^2 + 4*m*x8*cos(x4)*sin(x4)*L^2*M*R^2 + 4*Jm*x8*cos(x4)*sin(x4)*L^2*M*n^2 + 4*Jw*x8*cos(x4)*sin(x4)*L^2*M)/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4));
% 0,                                                                                                                                                                                                                                                                                                                            0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0,                                                                                                                                                                                                                                                                                                                                                             0, 0,                                                                                                                                                                                                                                                                                                                                                                  1;
% 0,                                                                                                                                                                                                                                                                                                                            0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    (4*L^2*M*R^2*cos(x4)*sin(x4)*(W^2*beta*x8 + W^2*fw*x8 + R*W*a*vl - R*W*a*vr + 4*L^2*M*R^2*x5*x8*cos(x4)*sin(x4)))/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2)^2 - (4*L^2*M*R^2*x5*x8*cos(x4)^2 - 4*L^2*M*R^2*x5*x8*sin(x4)^2)/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2),                                                                                                                                                                                                                                                     -(4*L^2*M*R^2*x8*cos(x4)*sin(x4))/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2), 0,                                                                                                                                                                                                                                      -(W^2*beta + W^2*fw + 4*L^2*M*R^2*x5*cos(x4)*sin(x4))/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2)]
 %Ma tr?n A t?i ?i?m cân b?ng (Thay các giá tr? trên vào trong bi?u th?c) 
A = [0,                                                                                                                                                                                                                                                                1,                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                    0, 0,                                                                    0;
0, -(2*J_psi*beta + 2*J_psi*fw + 2*L^2*M*beta + 2*L^2*M*fw + 4*Jm*fw*n^2 + 2*L*M*R*beta)/(2*J_psi*Jw + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 + 4*Jm*L*M*R*n^2),                             -(R*g*L^2*M^2 - 2*Jm*g*L*M*n^2)/(2*J_psi*Jw + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 + 4*Jm*L*M*R*n^2),              (2*M*beta*L^2 + 2*M*R*beta*L + 2*J_psi*beta)/(2*J_psi*Jw + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 + 4*Jm*L*M*R*n^2), 0,                                                                    0;
0,                                                                                                                                                                                                                                                                0,                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                    1, 0,                                                                    0;
0,   (4*Jw*beta + 2*M*R^2*beta - 4*Jm*fw*n^2 + 4*R^2*beta*m + 2*L*M*R*beta + 2*L*M*R*fw)/(2*J_psi*Jw + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 + 4*Jm*L*M*R*n^2), (L*g*M^2*R^2 + 2*L*g*m*M*R^2 + 2*Jm*L*g*M*n^2 + 2*Jw*L*g*M)/(2*J_psi*Jw + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 + 4*Jm*L*M*R*n^2), -(4*Jw*beta + 2*M*R^2*beta + 4*R^2*beta*m + 2*L*M*R*beta)/(2*J_psi*Jw + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 + 4*Jm*L*M*R*n^2), 0,                                                                    0;
0,                                                                                                                                                                                                                                                                0,                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                    0, 0,                                                                    1;
0,                                                                                                                                                                                                                                                                0,                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                    0, 0, -(W^2*beta + W^2*fw)/(m*R^2*W^2 + 2*J_phi*R^2 + Jm*W^2*n^2 + Jw*W^2)]

%% Tính ma tr?n B
% Tính ma tr?n B
% B = [ diff(y1,vl) diff(y1,vr);
%       diff(y2,vl) diff(y2,vr);
%       diff(y3,vl) diff(y3,vr);
%       diff(y4,vl) diff(y4,vr);
%       diff(y5,vl) diff(y5,vr);
%       diff(y6,vl) diff(y6,vr)]
%   
% Ra ma tr?n B theo symbols
% syms m M R Jw n Jm L n a beta fw g W J_psi Jw vl vr J_phi x1 x2 x3 x4 x5 x6 x7 x8 x9
% vl=0; vr=0; x1=0; x2=0; x3=0; x4=0; x5=0; x6=0; x7=0; x8=0; 
%  B =[                                                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                                          0;
%             (M*a*L^2 + M*R*a*cos(x4)*L + J_psi*a)/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)),             (M*a*L^2 + M*R*a*cos(x4)*L + J_psi*a)/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4));
%                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                                                                          0;
% -(2*Jw*a + M*R^2*a + 2*R^2*a*m + L*M*R*a*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4)), -(2*Jw*a + M*R^2*a + 2*R^2*a*m + L*M*R*a*cos(x4))/(2*J_psi*Jw + L^2*M^2*R^2 + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 - L^2*M^2*R^2*cos(x4)^2 + 4*Jm*L*M*R*n^2*cos(x4));
%                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                                                                          0;
%                                                                                                                                                                                           -(R*W*a)/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2),                                                                                                                                                                                            (R*W*a)/(2*J_phi*R^2 + Jw*W^2 + Jm*W^2*n^2 + R^2*W^2*m + 2*L^2*M*R^2*sin(x4)^2)]
% Ra ma tr?n B t?i ?i?m cân b?ng (Thay các giá tr? trên vào trong bi?u th?c)
B =[                                                                                                                                                                                                                   0,                                                                                                                                                                                                                    0;
            (M*a*L^2 + M*R*a*L + J_psi*a)/(2*J_psi*Jw + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 + 4*Jm*L*M*R*n^2),             (M*a*L^2 + M*R*a*L + J_psi*a)/(2*J_psi*Jw + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 + 4*Jm*L*M*R*n^2);
                                                                                                                                                                                                                   0,                                                                                                                                                                                                                    0;
-(2*Jw*a + M*R^2*a + 2*R^2*a*m + L*M*R*a)/(2*J_psi*Jw + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 + 4*Jm*L*M*R*n^2), -(2*Jw*a + M*R^2*a + 2*R^2*a*m + L*M*R*a)/(2*J_psi*Jw + 2*Jw*L^2*M + J_psi*M*R^2 + 2*J_psi*Jm*n^2 + 4*Jm*Jw*n^2 + 2*J_psi*R^2*m + 2*Jm*L^2*M*n^2 + 2*Jm*M*R^2*n^2 + 2*L^2*M*R^2*m + 4*Jm*R^2*m*n^2 + 4*Jm*L*M*R*n^2);
                                                                                                                                                                                                                   0,                                                                                                                                                                                                                    0;
                                                                                                                                                            -(R*W*a)/(m*R^2*W^2 + 2*J_phi*R^2 + Jm*W^2*n^2 + Jw*W^2),                                                                                                                                                              (R*W*a)/(m*R^2*W^2 + 2*J_phi*R^2 + Jm*W^2*n^2 + Jw*W^2)]
 
%% Ma tr?n A và B sau khi nh?p t?t c? các thông s? 
%Ma tr?n A
%   A =[   0    1.0000         0         0         0         0;
%          0   -0.9379   22.6678    0.0055         0         0;
%          0         0         0    1.0000         0         0;
%          0   -0.9222   22.7440   -0.0021         0         0;
%          0         0         0         0         0    1.0000;
%          0         0         0         0         0   -0.0188]
%Ma tr?n B
%  B =[    0          0;
%     0.0057    0.0057;
%          0         0;
%    -0.0022   -0.0022;
%          0         0;
%    -0.0048    0.0048]

%% Tính thông s? K c?a LQR
R__ = [1 0; 0 1]; %Ch?nn R__ vì ? trên ?ã có R là bán kính bánh xe r?i
Q = [ 1 0 0 0 0 0;
      0 1 0 0 0 0;
      0 0 1 0 0 0;
      0 0 0 1 0 0;
      0 0 0 0 1 0; 
      0 0 0 0 0 1]
 K = lqr(A,B,Q,R__)

% Ch?n thông s? ban ??u
x1_init = 0.001; x2_init = -0.0012; x4_init = 0.002; x5_init = -0.002; x7_init = 0.002; x8_init=-0.0014;

% 
x1_init = 0.01; x2_init = -0.012; x4_init = 0.2; x5_init = -0.02; x7_init = 0.04; x8_init=-0.03;
